kind: ConfigMap
apiVersion: v1
metadata:
  name: litfass-env-conf
  namespace: default
data:
  LITFASS_LOG_LEVEL: "INFO"
  LITFASS_USERS_ADMIN_PASSWORD: "admin"
  LITFASS_JDBC_URL: "jdbc:postgresql://cockroachdb-public:26257"
  LITFASS_JDBC_DATABASE: "litfass"
  LITFASS_JDBC_USERNAME: "litfass"
  LITFASS_JDBC_PASSWORD: "admin"
  LITFASS_JDBC_POOL_SIZE: "1"
  LITFASS_AKKA_REMOTE_CANONICAL_HOSTNAME: "litfass-cluster.default.svc.cluster.local"
  LITFASS_AKKA_REMOTE_CANONICAL_PORT: "25520"
  LITFASS_AKKA_REMOTE_BIND_HOSTNAME: "litfass-cluster.default.svc.cluster.local"
  LITFASS_AKKA_REMOTE_BIND_PORT: "25520"
  LITFASS_AKKA_CLUSTER_SERVICE_NAME: "litfass-cluster"
  LITFASS_AKKA_CLUSTER_SERVICE_NAMESPACE: "default.svc.cluster.local"
  LITFASS_AKKA_CLUSTER_REQUIRED_CONTACT_POINTS: "3"
  LITFASS_AKKA_MGMT_PORT: "8558"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: litfass
  namespace: default
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - litfass
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: litfass
        version: "2.0.0"
    spec:
      containers:
        - name: litfass
          image: aemaem/litfass:latest
#          image: aemaem/litfass:2.0.0 # todo: update
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "0.25"
              memory: "0.5G"
            limits:
              cpu: "0.75"
              memory: "1.5G"
          envFrom:
            - configMapRef:
                name: litfass-env-conf
          env:
            - name: LITFASS_AKKA_REMOTE_BIND_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 25520
              protocol: TCP
            - containerPort: 8558
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            successThreshold: 3
---
kind: Service
apiVersion: v1
metadata:
  name: litfass-cluster
  namespace: default
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: akka-remote
      port: 25520
      targetPort: 25520
      protocol: TCP
    - name: akka-mgmt
      port: 8558
      targetPort: 8558
      protocol: TCP
  selector:
    app: litfass
  clusterIP: None
  publishNotReadyAddresses: true
---
kind: Service
apiVersion: v1
metadata:
  name: litfass
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: litfass
