version: "2"
services:
  litfass-server:
    image: aemaem/litfass:0.7.7
    depends_on:
      - litfass-postgres
      - litfass-elasticsearch
    restart: always
    container_name: "litfass-server"
    hostname: "litfass-server"
    volumes:
      - /home/mmair/Downloads/litfass/conf:/var/litfass/conf
      - /home/mmair/Downloads/litfass/ext:/var/litfass/ext
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: "AKIAQDJZAQLNDQ2JXKEK"
      AWS_SECRET_ACCESS_KEY: "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"
    networks:
      - litfass
  litfass-postgres:
    image: postgres:11.1-alpine
    restart: always
    container_name: "litfass-postgresql"
    hostname: "litfass-postgresql"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: litfass
    networks:
      - litfass
  litfass-elasticsearch:
    image: elasticsearch:6.5.1
    container_name: "litfass-elasticsearch"
    hostname: "litfass-elasticsearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      "discovery.type": "single-node"
    networks:
      - litfass
  litfass-grafana:
    image: grafana/grafana:5.4.2
    restart: always
    container_name: "litfass-grafana"
    hostname: "litfass-grafana"
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "vonage-status-panel,jdbranham-diagram-panel,grafana-piechart-panel"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    networks:
      - litfass

networks:
  litfass:
    driver: bridge