version: 2
machine: true
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers
      - image: docker:stable-git
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "build.gradle.kts" }}-{{ checksum "litfass-server/litfass-server.gradle.kts" }}
      - run:
          name: "Test"
          command: ./gradlew unitTest --stacktrace
      - run:
          name: "Collect test results"
          when: always
          command: mkdir -p build/circleci/test-results && find . -type f -regex ".*/build/test-results/*Test/.*xml" -exec cp {} build/circleci/test-results \;
      - run:
          name: "Build"
          command: ./gradlew assemble --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: cache-{{ checksum "build.gradle.kts" }}-{{ checksum "litfass-server/litfass-server.gradle.kts" }}
      - store_test_results:
          path: build/circleci/test-results
  release:
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers
      - image: docker:stable-git
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: cache-{{ checksum "build.gradle.kts" }}-{{ checksum "litfass-server/litfass-server.gradle.kts" }}
      - run:
          name: "Build, release and publish"
          command: ./gradlew final -Prelease.useLastTag=true pushImage --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: cache-{{ checksum "build.gradle.kts" }}-{{ checksum "litfass-server/litfass-server.gradle.kts" }}

workflows:
  version: 2
  default:
    jobs:
      - build
      - release:
          context: docker-hub
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
