name: Build and Test
on: [ push ]

jobs:
  build-server:
    runs-on: ubuntu-18.04
    environment: default
    env:
      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"'
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_EMAIL: ${{ secrets.DOCKER_HUB_EMAIL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
          java-package: jdk
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit Test
        run: ./gradlew unitTest --stacktrace
      - name: Upload unit test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          retention-days: 7
          path: litfass-server/build/reports/tests/unitTest
      - name: Integration Test
        run: ./gradlew integrationTest --stacktrace
      - name: Upload integration test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: integration-test-report
          retention-days: 7
          path: litfass-server/build/reports/tests/integrationTest
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: cache-gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
      - name: Build
        run: ./gradlew assemble buildImage --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: executable
          path: litfass-server/build/libs
      - name: API Test
        run: ./gradlew apiTest --stacktrace
      - name: Upload API test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: api-test-report
          retention-days: 7
          path: litfass-server/build/reports/tests/apiTest

  build-grafana-plugin:
    runs-on: ubuntu-18.04
    environment: default
    # todo: implement correctly
#    env:
#      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"'
#      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
#      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
#      DOCKER_HUB_EMAIL: ${{ secrets.DOCKER_HUB_EMAIL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          java-package: jdk
          architecture: x64
      - name: Change directory to grafana plugin root
        run: cd litfass-grafana-plugin
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
#      - name: Upload test report
#        if: ${{ always() }}
#        uses: actions/upload-artifact@v2
#        with:
#          name: unit-test-report
#          retention-days: 7
#          path: litfass-server/build/reports/tests/unitTest
#      - name: Cache dependencies
#        uses: actions/cache@v2
#        with:
#          path: ~/.gradle/caches
#          key: cache-gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
#          restore-keys: cache-gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
      - name: Build
        run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: executable
          path: litfass-grafan-plugin/dist
#      - name: API Test
#        run: ./gradlew apiTest --stacktrace
#      - name: Upload API test report
#        if: ${{ always() }}
#        uses: actions/upload-artifact@v2
#        with:
#          name: api-test-report
#          retention-days: 7
#          path: litfass-server/build/reports/tests/apiTest
