name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
          java-package: jdk
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit Test
        run: ./gradlew unitTest --stacktrace
      - name: Upload unit test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          retention-days: 7
          path: litfass-server/build/reports/tests/unitTest
      - name: Integration Test
        run: ./gradlew integrationTest --stacktrace
      - name: Upload integration test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: integration-test-report
          retention-days: 7
          path: litfass-server/build/reports/tests/integrationTest
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: cache-gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
      - name: Build
        run: ./gradlew assemble buildImage --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: executable
          path: litfass-server/build/libs
      - name: API Test
        run: ./gradlew apiTest --stacktrace
      - name: Upload API test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: api-test-report
          retention-days: 7
          path: litfass-server/build/reports/tests/apiTest
