name: Release
on:
  workflow_dispatch:
    inputs:
      scope:
        description: "Scope (e.g. major, minor, patch)"
        required: true
        default: minor

jobs:
  release:
    runs-on: ubuntu-18.04
    environment: default
    env:
      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"'
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_EMAIL: ${{ secrets.DOCKER_HUB_EMAIL }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
          java-package: jdk
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: cache-gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
      - name: Release
        run: ./gradlew final -Prelease.scope=${{ github.event.inputs.scope }} pushImage --stacktrace
