name: release
on:
  workflow_dispatch:
    inputs:
      scope:
        description: "Scope (e.g. major, minor, patch)"
        required: true
        default: minor

jobs:
  environment: default
  release:
    runs-on: ubuntu-18.04
    env:
      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
          java-package: jdk
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: cache-gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
      - name: Release
        run: ./gradlew final -Prelease.scope=${{ github.event.inputs.scope }} pushImage --stacktrace
      #todo: https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Publish
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: aemaem/litfass
          tags: latest